// Package remote connects to conch servers on other machines over the
// system's OpenSSH: it probes the machine, installs conch there when needed,
// and bridges the protocol through `conch bridge`.
package remote

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/Amitgb14/conch/internal/config"
)

// sshBinary is the ssh client; $CONCH_SSH overrides it.
func sshBinary() string {
	if b := os.Getenv("CONCH_SSH"); b != "" {
		return b
	}
	return "ssh"
}

var configOnce struct {
	sync.Mutex
	path string
}

// sshConfig writes the ssh config conch uses and returns its path. It
// includes the system and user configs first, so anything the user set
// wins; conch only adds keepalives and connection sharing on top.
// $CONCH_SSH_CONFIG names an extra config included before the user's.
func sshConfig() (string, error) {
	configOnce.Lock()
	defer configOnce.Unlock()
	if configOnce.path != "" {
		return configOnce.path, nil
	}
	dir := filepath.Join(config.Dir(), "ssh")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	// Control sockets need a short path (unix socket limit), so they live
	// in a private directory under /tmp rather than the config dir.
	ctl := filepath.Join(os.TempDir(), fmt.Sprintf("conch-ssh-%d", os.Getuid()))
	if len(ctl) > 40 {
		ctl = fmt.Sprintf("/tmp/conch-ssh-%d", os.Getuid())
	}
	if err := os.MkdirAll(ctl, 0o700); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by conch; rewritten on every start.\n")
	if extra := os.Getenv("CONCH_SSH_CONFIG"); extra != "" {
		fmt.Fprintf(&b, "Include %s\n", quoteConfig(extra))
	}
	if home, err := os.UserHomeDir(); err == nil {
		if user := filepath.Join(home, ".ssh", "config"); exists(user) {
			fmt.Fprintf(&b, "Include %s\n", quoteConfig(user))
		}
	}
	if exists("/etc/ssh/ssh_config") {
		b.WriteString("Include /etc/ssh/ssh_config\n")
	}
	fmt.Fprintf(&b, `
Host *
  ServerAliveInterval 15
  ServerAliveCountMax 3
  ControlMaster auto
  ControlPath %s/%%C
  ControlPersist 60
`, quoteConfig(ctl))
	// The key conch made for machines when the user had none (see
	// SetUpKeyLogin). Only then: naming a key stops ssh trying the defaults.
	if key := conchKey(); exists(key) {
		fmt.Fprintf(&b, "  IdentityFile %s\n", quoteConfig(key))
	}

	path := filepath.Join(dir, "config")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", err
	}
	configOnce.path = path
	return path, nil
}

func quoteConfig(s string) string {
	if strings.ContainsAny(s, " \t\"") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// sshCmd builds an ssh invocation running script on target. Interactive
// runs may prompt (passwords, host keys) on the terminal; background runs
// fail instead.
func sshCmd(ctx context.Context, target, script string, interactive bool) (*exec.Cmd, error) {
	return sshCmdWith(ctx, target, script, sshOpts{interactive: interactive})
}

// sshOpts say how ssh may authenticate.
type sshOpts struct {
	// interactive lets ssh prompt on the terminal.
	interactive bool
	// askpass answers a password prompt without a terminal (adding a
	// machine from the TUI); the host's key is accepted the first time.
	askpass *askpass
	// keyOnly succeeds only through key login: no password, no shared
	// connection that another command already authenticated.
	keyOnly bool
}

func sshCmdWith(ctx context.Context, target, script string, o sshOpts) (*exec.Cmd, error) {
	cfg, err := sshConfig()
	if err != nil {
		return nil, err
	}
	args := []string{"-F", cfg, "-T"}
	switch {
	case o.askpass != nil:
		args = append(args, "-o", "BatchMode=no", "-o", "NumberOfPasswordPrompts=1",
			"-o", "StrictHostKeyChecking=accept-new", "-o", "ConnectTimeout=15")
	case o.keyOnly:
		args = append(args, "-o", "BatchMode=yes", "-o", "ControlPath=none", "-o", "PasswordAuthentication=no",
			"-o", "KbdInteractiveAuthentication=no", "-o", "ConnectTimeout=10")
	case !o.interactive:
		args = append(args, "-o", "BatchMode=yes", "-o", "ConnectTimeout=10")
	}
	args = append(args, "--", target, script)
	cmd := exec.CommandContext(ctx, sshBinary(), args...)
	if o.askpass != nil {
		cmd.Env = o.askpass.env()
	}
	// A ControlPersist master inherits our pipes and outlives this command;
	// don't wait for it to close them.
	cmd.WaitDelay = 2 * time.Second
	return cmd, nil
}

// LoginCommand is the command for an interactive ssh session to target in
// a terminal: conch's ssh config (the user's own first), no remote command.
func LoginCommand(target string) ([]string, error) {
	if err := CheckLoginTarget(target); err != nil {
		return nil, err
	}
	cfg, err := sshConfig()
	if err != nil {
		return nil, err
	}
	return []string{sshBinary(), "-F", cfg, "--", target}, nil
}

// CheckLoginTarget rejects what ssh would not read as a single host: empty
// text, spaces, control characters, and a leading "-" that ssh could take
// for an option.
func CheckLoginTarget(target string) error {
	switch {
	case target == "":
		return fmt.Errorf("an ssh host is required")
	case strings.HasPrefix(target, "-"):
		return fmt.Errorf("an ssh host can't start with -")
	case strings.IndexFunc(target, func(r rune) bool { return r <= ' ' || r == 0x7f }) >= 0:
		return fmt.Errorf("an ssh host can't contain spaces or control characters")
	}
	return nil
}

// IsLoginCommand reports whether a pane's command is an ssh session.
func IsLoginCommand(command []string) bool {
	return len(command) > 0 && filepath.Base(command[0]) == "ssh"
}

// run executes script on target and returns its stdout.
func run(ctx context.Context, target, script string, stdin []byte, interactive bool) ([]byte, error) {
	return runWith(ctx, target, script, stdin, sshOpts{interactive: interactive})
}

func runWith(ctx context.Context, target, script string, stdin []byte, o sshOpts) ([]byte, error) {
	interactive := o.interactive && o.askpass == nil
	cmd, err := sshCmdWith(ctx, target, script, o)
	if err != nil {
		return nil, err
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if stdin != nil {
		cmd.Stdin = bytes.NewReader(stdin)
	} else if interactive {
		cmd.Stdin = os.Stdin
	}
	if interactive {
		cmd.Stderr = os.Stderr // let ssh talk to the user
	}
	if err := cmd.Run(); err != nil {
		return stdout.Bytes(), sshError(err, stderr.String())
	}
	return stdout.Bytes(), nil
}

// sshError turns a failed ssh run into a readable error.
func sshError(err error, stderr string) error {
	msg := strings.TrimSpace(stderr)
	if lines := strings.Split(msg, "\n"); len(lines) > 3 {
		msg = strings.Join(lines[len(lines)-3:], "\n")
	}
	if msg == "" {
		return err
	}
	if strings.Contains(msg, "Permission denied") || strings.Contains(msg, "Host key verification failed") {
		msg += " (run `conch machine add` in a terminal once to answer ssh prompts, or load your key with ssh-add)"
	}
	return fmt.Errorf("%s", msg)
}
