// Package remote connects to conch servers on other machines over the
// system's OpenSSH: it probes the machine, installs conch there when needed,
// and bridges the protocol through `conch bridge`.
package remote

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/Amitgb14/conch/internal/config"
)

// sshBinary is the ssh client; $CONCH_SSH overrides it.
func sshBinary() string {
	if b := os.Getenv("CONCH_SSH"); b != "" {
		return b
	}
	return "ssh"
}

var configOnce struct {
	sync.Mutex
	path string
}

// sshConfig writes the ssh config conch uses and returns its path. It
// includes the system and user configs first, so anything the user set
// wins; conch only adds keepalives and connection sharing on top.
// $CONCH_SSH_CONFIG names an extra config included before the user's.
func sshConfig() (string, error) {
	configOnce.Lock()
	defer configOnce.Unlock()
	if configOnce.path != "" {
		return configOnce.path, nil
	}
	dir := filepath.Join(config.Dir(), "ssh")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	// Control sockets need a short path (unix socket limit), so they live
	// in a private directory under /tmp rather than the config dir.
	ctl := filepath.Join(os.TempDir(), fmt.Sprintf("conch-ssh-%d", os.Getuid()))
	if len(ctl) > 40 {
		ctl = fmt.Sprintf("/tmp/conch-ssh-%d", os.Getuid())
	}
	if err := os.MkdirAll(ctl, 0o700); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by conch; rewritten on every start.\n")
	if extra := os.Getenv("CONCH_SSH_CONFIG"); extra != "" {
		fmt.Fprintf(&b, "Include %s\n", quoteConfig(extra))
	}
	if home, err := os.UserHomeDir(); err == nil {
		if user := filepath.Join(home, ".ssh", "config"); exists(user) {
			fmt.Fprintf(&b, "Include %s\n", quoteConfig(user))
		}
	}
	if exists("/etc/ssh/ssh_config") {
		b.WriteString("Include /etc/ssh/ssh_config\n")
	}
	fmt.Fprintf(&b, `
Host *
  ServerAliveInterval 15
  ServerAliveCountMax 3
  ControlMaster auto
  ControlPath %s/%%C
  ControlPersist 60
`, quoteConfig(ctl))
	// The keys to log in with: conch's own, made when the user had none
	// (see SetUpKeyLogin), and the user's defaults. Naming any key stops
	// ssh trying the defaults, so once conch's key exists the user's would
	// never be offered — and a machine authorized with the user's key, a
	// sandbox among them, would refuse a login it was set up to allow.
	for _, key := range loginKeys() {
		fmt.Fprintf(&b, "  IdentityFile %s\n", quoteConfig(key))
	}

	// Other conch processes may be running ssh -F on this file right now;
	// replace it whole rather than truncating it under them.
	path := filepath.Join(dir, "config")
	if err := writeFileAtomic(path, []byte(b.String())); err != nil {
		return "", err
	}
	configOnce.path = path
	return path, nil
}

func quoteConfig(s string) string {
	if strings.ContainsAny(s, " \t\"") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// sshCmd builds an ssh invocation running script on target. Interactive
// runs may prompt (passwords, host keys) on the terminal; background runs
// fail instead.
func sshCmd(ctx context.Context, target, script string, interactive bool) (*exec.Cmd, error) {
	return sshCmdWith(ctx, target, script, sshOpts{interactive: interactive})
}

// sshOpts say how ssh may authenticate.
type sshOpts struct {
	// interactive lets ssh prompt on the terminal.
	interactive bool
	// askpass answers a password prompt without a terminal (adding a
	// machine from the TUI); the host's key is accepted the first time.
	askpass *askpass
	// keyOnly succeeds only through key login: no password, no shared
	// connection that another command already authenticated.
	keyOnly bool
	// acceptNew takes a host's key the first time without asking, for a
	// gateway nobody is there to vouch for (a sandbox provider's).
	acceptNew bool
	// identity is the private key to log in with, and only that one: where
	// conch authorized a key itself it must offer that key, since the
	// generated config names conch's own and so stops ssh trying the
	// defaults, and the agent may hold nothing.
	identity string
}

func sshCmdWith(ctx context.Context, target, script string, o sshOpts) (*exec.Cmd, error) {
	cfg, err := sshConfig()
	if err != nil {
		return nil, err
	}
	args := []string{"-F", cfg, "-T"}
	switch {
	case o.askpass != nil:
		args = append(args, "-o", "BatchMode=no", "-o", "NumberOfPasswordPrompts=1",
			"-o", "StrictHostKeyChecking=accept-new", "-o", "ConnectTimeout=15")
	case o.keyOnly:
		args = append(args, "-o", "BatchMode=yes", "-o", "ControlPath=none", "-o", "PasswordAuthentication=no",
			"-o", "KbdInteractiveAuthentication=no", "-o", "ConnectTimeout=10")
	case !o.interactive:
		args = append(args, "-o", "BatchMode=yes", "-o", "ConnectTimeout=10")
		if o.acceptNew {
			args = append(args, "-o", "StrictHostKeyChecking=accept-new")
		}
	}
	if o.identity != "" {
		args = append(args, "-i", o.identity, "-o", "IdentitiesOnly=yes")
	}
	args = append(args, "--", target, script)
	cmd := exec.CommandContext(ctx, sshBinary(), args...)
	if o.askpass != nil {
		cmd.Env = o.askpass.env()
	}
	// A ControlPersist master inherits our pipes and outlives this command;
	// don't wait for it to close them.
	cmd.WaitDelay = 2 * time.Second
	return cmd, nil
}

// LoginCommand is the command for an interactive ssh session to target in
// a terminal: conch's ssh config (the user's own first), no remote command.
// The session makes its own connection, as a plain ssh would: sharing
// conch's master meant that once the host stopped answering, a new login
// sat on a blank screen until the dead master timed out, about a minute.
func LoginCommand(target string) ([]string, error) {
	if err := CheckLoginTarget(target); err != nil {
		return nil, err
	}
	cfg, err := sshConfig()
	if err != nil {
		return nil, err
	}
	return []string{sshBinary(), "-F", cfg, "-o", "ControlPath=none", "--", target}, nil
}

// CheckLoginTarget rejects what ssh would not read as a single host: empty
// text, spaces, control characters, and a leading "-" that ssh could take
// for an option.
func CheckLoginTarget(target string) error {
	switch {
	case target == "":
		return fmt.Errorf("an ssh host is required")
	case strings.HasPrefix(target, "-"):
		return fmt.Errorf("an ssh host can't start with -")
	case strings.IndexFunc(target, func(r rune) bool { return r <= ' ' || r == 0x7f }) >= 0:
		return fmt.Errorf("an ssh host can't contain spaces or control characters")
	}
	return nil
}

// IsLoginCommand reports whether a pane's command is an ssh session.
func IsLoginCommand(command []string) bool {
	return len(command) > 0 && filepath.Base(command[0]) == "ssh"
}

// sshError turns a failed ssh run into a readable error.
func sshError(err error, stderr string) error {
	msg := strings.TrimSpace(stderr)
	if lines := strings.Split(msg, "\n"); len(lines) > 3 {
		msg = strings.Join(lines[len(lines)-3:], "\n")
	}
	// 255 is ssh's own code for "the connection failed", as against a
	// remote command that ran and returned something. It can come with
	// nothing on stderr at all — a gateway closing on a machine that has
	// only just started — and then "exit status 255" is all anybody sees.
	if sshConnectionFailed(err) {
		return &ConnectionError{Err: err, Stderr: msg}
	}
	if msg == "" {
		return err
	}
	if strings.Contains(msg, "Permission denied") || strings.Contains(msg, "Host key verification failed") {
		msg += " (run `conch machine add` in a terminal once to answer ssh prompts, or load your key with ssh-add)"
	}
	return fmt.Errorf("%s", msg)
}

// sshConnectionFailed reports ssh's own "could not connect" exit code.
func sshConnectionFailed(err error) bool {
	var exit *exec.ExitError
	return errors.As(err, &exit) && exit.ExitCode() == 255
}

// ConnectionError is ssh failing to connect rather than a command failing:
// worth trying again, since a sandbox that has only just been made may not
// be answering yet, and a long copy can be dropped.
type ConnectionError struct {
	Err    error
	Stderr string
}

func (e *ConnectionError) Error() string {
	if e.Stderr != "" {
		if strings.Contains(e.Stderr, "Permission denied") || strings.Contains(e.Stderr, "Host key verification failed") {
			return e.Stderr + " (run `conch machine add` in a terminal once to answer ssh prompts, or load your key with ssh-add)"
		}
		return e.Stderr
	}
	return "the ssh connection failed (255), with nothing said: the machine may not be answering yet"
}

func (e *ConnectionError) Unwrap() error { return e.Err }
